image: golang:latest
stages:
  - build

before_script:
  - go get -u "golang.org/x/net/html"
  - cd /builds/bestmethod/webCrawler
  - mkdir -p bin/linux
  - mkdir bin/osx
  - mkdir bin/windows

build:
  stage: build
  script:
    - env GOOS=linux GOARCH=amd64 go build -o bin/linux/crawler
    - env GOOS=darwin GOARCH=amd64 go build -o bin/osx/crawler
    - env GOOS=windows GOARCH=amd64 go build -o bin/windows/crawler
  artifacts:
    paths:
      - bin/linux
      - bin/osx
      - bin/windows
